version: "3.9"

volumes:
  db_data: {}

services:
  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/1.sql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    ports:
      - "3306:3306"
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"  
  api:
    depends_on:
      - db
      - redis
    build: .
    restart: always
    ports:
      - "8080:8080"