FROM golang:alpine as builder

WORKDIR /app

COPY . /app

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/worker ./cmd/worker/...

FROM gcr.io/distroless/static as final

WORKDIR /app

USER nonroot:nonroot

COPY --from=builder --chown=nonroot:nonroot /app/worker /usr/bin/worker

ENTRYPOINT [ "/usr/bin/worker" ]